"""Type definitions for mememo."""

from .config import (
    ChunkingConfig,
    Config,
    EmbeddingConfig,
    IndexingConfig,
    SearchConfig,
    SecurityConfig,
    StorageConfig,
)
from .memory import (
    BACKFILL_SHA,
    NULL_SHA,
    SHA_PATTERN,
    SHA_PREFIX_PATTERN,
    BranchContext,
    BranchState,
    CreateMemoryParams,
    GitContext,
    Memory,
    MemoryContent,
    MemoryContentType,
    MemoryEvent,
    MemoryEventOp,
    MemoryFilters,
    MemoryMetadata,
    MemoryRelationships,
    MemorySummary,
    Relation,
    RelationConfidence,
    RelationType,
    RepoContext,
    RiskGrade,
    SearchParams,
    SearchResult,
    SummarizeParams,
    coerce_sha,
)

__all__ = [
    # Config types
    "Config",
    "StorageConfig",
    "EmbeddingConfig",
    "ChunkingConfig",
    "SearchConfig",
    "SecurityConfig",
    "IndexingConfig",
    # Memory types
    "RepoContext",
    "BranchContext",
    "GitContext",
    "MemoryContentType",
    "MemoryContent",
    "MemoryMetadata",
    "MemoryRelationships",
    "MemorySummary",
    "Memory",
    "CreateMemoryParams",
    "MemoryFilters",
    "SearchParams",
    "SummarizeParams",
    "SearchResult",
    # v0.4.0 commit-aware additions
    "RiskGrade",
    "MemoryEventOp",
    "MemoryEvent",
    "BranchState",
    "NULL_SHA",
    "BACKFILL_SHA",
    "SHA_PATTERN",
    "SHA_PREFIX_PATTERN",
    "coerce_sha",
    # v0.5.0 graph layer
    "Relation",
    "RelationType",
    "RelationConfidence",
]
